name: test-push.yml
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
jobs:
  build:
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: test
        run: |
          echo 'test'
